Repository HPInc/aistudio-galileo-templates, pull requests merged in 2025-05, with the labels that each got.

#26 Fix: Galileo Protect
  02-code-generation-with-langchain/notebooks/code-generation-with-langchain.ipynb
Labels: bug

#22 Fine-tuning Framework: LoRA + ORPO + QLoRA with Multi-Model Support
  05-fine-tuning-orpo/README.md
  05-fine-tuning-orpo/notebooks/config/default_config-cpu.yaml
  05-fine-tuning-orpo/notebooks/config/default_config_multi-gpu.yaml
  05-fine-tuning-orpo/notebooks/config/default_config_one-gpu.yaml
  05-fine-tuning-orpo/notebooks/core/comparer/galileo_hf_model_comparer.py
  05-fine-tuning-orpo/notebooks/core/data_visualizer/feedback_visualizer.py
  05-fine-tuning-orpo/notebooks/core/deploy/deploy_fine_tuning.py
  05-fine-tuning-orpo/notebooks/core/finetuning_inference/inference_runner.py
  05-fine-tuning-orpo/notebooks/core/ggml_convert/convert-lora-to-ggml.py
  05-fine-tuning-orpo/notebooks/core/ggml_convert/convert.py
  05-fine-tuning-orpo/notebooks/core/local_inference/inference.py
  05-fine-tuning-orpo/notebooks/core/merge_model/merge_lora.py
  05-fine-tuning-orpo/notebooks/core/quantization/quantization_config.py
  05-fine-tuning-orpo/notebooks/core/selection/model_selection.py
  05-fine-tuning-orpo/notebooks/core/target_mapper/lora_target_mapper.py
  05-fine-tuning-orpo/notebooks/fine_tuning_orpo.ipynb
  05-fine-tuning-orpo/requirements.txt
  src/utils.py
Labels: enhancement

#32 Fix: Proxy error Image Generation
  04-image-generation/notebooks/core/custom_metrics/image_metrics_scorers.py
  04-image-generation/notebooks/core/deploy/deploy_image_generation.py
  04-image-generation/notebooks/core/train/train_dreambooth_aistudio.py
  04-image-generation/notebooks/inference.ipynb
Labels: bug

#30 [feature, refactor] streamlit ui added, slight prompt engineering imp…
  00-vanilla-rag-with-langchain-and-galileo/README.md
  00-vanilla-rag-with-langchain-and-galileo/core/chatbot_service/chatbot_service.py
  00-vanilla-rag-with-langchain-and-galileo/demo/vanilla-rag-streamlit-webapp/README.md
  00-vanilla-rag-with-langchain-and-galileo/demo/vanilla-rag-streamlit-webapp/main.py
  00-vanilla-rag-with-langchain-and-galileo/demo/vanilla-rag-streamlit-webapp/poetry.lock
  00-vanilla-rag-with-langchain-and-galileo/demo/vanilla-rag-streamlit-webapp/pyproject.toml
  00-vanilla-rag-with-langchain-and-galileo/docs/html_ui_for_vanilla_rag.png
  00-vanilla-rag-with-langchain-and-galileo/docs/streamlit_ui_for_vanilla_rag.png.png
  00-vanilla-rag-with-langchain-and-galileo/docs/successful streamlit ui result for vanilla rag.pdf
Labels: enhancement

#33 [feat] Fixing sentence transformers embeddings bug
  00-vanilla-rag-with-langchain-and-galileo/core/chatbot_service/chatbot_service.py
  00-vanilla-rag-with-langchain-and-galileo/notebooks/vanilla-rag-with-langchain-and-galileo.ipynb
  02-code-generation-with-langchain/notebooks/code-generation-with-langchain.ipynb
  02-code-generation-with-langchain/notebooks/core/code_generation_service.py
  03-text-generation-with-langchain/notebooks/text-generation-with-langchain.ipynb
  src/utils.py
Labels: bug, enhancement

#35 feat(streamlit): add deployment scripts for Streamlit demo
  03-text-generation-with-langchain/README.md
  03-text-generation-with-langchain/demo/README.md
  03-text-generation-with-langchain/demo/main.py
  03-text-generation-with-langchain/demo/poetry.lock
  03-text-generation-with-langchain/demo/pyproject.toml
  03-text-generation-with-langchain/docs/successful_streamlit_sucess._ui_result.png
  03-text-generation-with-langchain/docs/successful_streamlit_ui_result.pdf
  03-text-generation-with-langchain/notebooks/core/deploy/text_generation_service.py
  03-text-generation-with-langchain/notebooks/core/generator/script_generator.py
  03-text-generation-with-langchain/notebooks/text-generation-with-langchain.ipynb
Labels: enhancement
